# Generated by Django 4.2.15 on 2024-10-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_alter_category_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
