# Generated by Django 4.2.15 on 2024-11-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0003_alter_category_description_alter_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
