# Generated by Django 4.2.15 on 2024-10-06 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("transaction_number", models.CharField(max_length=255)),
                ("total_cost", models.FloatField()),
                ("order_date", models.DateTimeField()),
                ("order_status", models.CharField(max_length=50)),
                ("gst_amount", models.FloatField()),
                ("shipping_cost", models.FloatField()),
                ("location_pickup", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
