# Generated by Django 4.2.15 on 2024-10-16 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_remove_order_deleted_at_order_delete_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="recipient_name",
            field=models.CharField(default="Unknown name", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="recipient_phone",
            field=models.CharField(default="Unknown phone", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(default="Unknown Recipient", max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
