# Generated by Django 4.2.15 on 2024-10-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_order_recipient_name_order_recipient_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="location_pickup",
        ),
        migrations.RemoveField(
            model_name="order",
            name="transaction_number",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cash_on_delivery", "Cash on Delivery"),
                    ("e_wallet", "E-Wallet"),
                ],
                default="credit_card",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("paid", "Paid"), ("failed", "Failed")],
                default="unpaid",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("returned", "Returned"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
