# Generated by Django 4.2.15 on 2024-10-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_remove_order_location_pickup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cash_on_delivery", "Cash on Delivery"),
                    ("e_wallet", "E-Wallet"),
                ],
                default="cash_on_delivery",
                max_length=50,
            ),
        ),
    ]
