# Generated by Django 4.2.15 on 2024-10-06 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_category_blog_my_admin"),
        ("tag", "0001_initial"),
        ("blog_tag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogtag",
            name="blog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.blog",
            ),
        ),
        migrations.AddField(
            model_name="blogtag",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tag.tag",
            ),
        ),
    ]
