# Generated by Django 4.2.15 on 2024-10-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_tag", "0002_alter_blogtag_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogtag",
            name="delete_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="blogtag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
