# Generated by Django 4.2.15 on 2024-10-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_payment_guest_payment_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="deleted_at",
        ),
        migrations.AddField(
            model_name="payment",
            name="delete_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
