# Generated by Django 4.2.15 on 2024-11-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0002_alter_tag_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
