# Generated by Django 4.2.15 on 2024-10-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_remove_store_deleted_at_store_delete_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
