# Generated by Django 4.2.15 on 2024-11-03 16:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("my_admin", "0001_initial"),
        ("promotion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("launch_date", models.DateField(blank=True, null=True)),
                ("short_description", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.CharField(max_length=255)),
                ("gallery", models.TextField()),
                ("price", models.FloatField()),
                ("color", models.CharField(max_length=255)),
                ("product_type", models.CharField(max_length=255)),
                ("screen_size", models.DecimalField(decimal_places=1, max_digits=3)),
                ("screen_technology", models.CharField(max_length=100)),
                ("resolution", models.CharField(max_length=50)),
                ("screen_features", models.TextField()),
                ("main_camera", models.CharField(max_length=255)),
                (
                    "telephoto_camera",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ultra_wide_camera",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("video_recording", models.TextField()),
                ("camera_features", models.TextField()),
                ("front_camera", models.CharField(max_length=255)),
                ("chipset", models.CharField(max_length=100)),
                ("gpu", models.CharField(max_length=100)),
                ("nfc", models.BooleanField(default=False)),
                ("sim_type", models.CharField(max_length=50)),
                ("network_support", models.CharField(max_length=50)),
                ("gps_support", models.CharField(max_length=255)),
                ("storage_capacity", models.IntegerField()),
                ("dimensions", models.CharField(max_length=50)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("back_material", models.CharField(max_length=50)),
                ("frame_material", models.CharField(max_length=50)),
                ("water_resistance", models.CharField(max_length=50)),
                ("os_version", models.CharField(max_length=50)),
                ("security_features", models.TextField()),
                ("other_features", models.TextField()),
                ("audio_technologies", models.TextField()),
                ("charging_technology", models.TextField()),
                ("charging_port", models.CharField(max_length=50)),
                ("wifi", models.CharField(max_length=50)),
                ("bluetooth", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delete_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="my_admin.myadmin",
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.catalog",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="promotion.promotion",
                    ),
                ),
            ],
            options={
                "db_table": "products",
            },
        ),
    ]
