# Generated by Django 4.2.15 on 2024-10-06 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sku", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=50)),
                ("part_number", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("short_description", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("product_type", models.TextField()),
                ("image", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("member_price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("gallery", models.TextField()),
                ("weight", models.FloatField()),
                ("diameter", models.FloatField()),
                ("dimensions", models.CharField(max_length=255)),
                ("material", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
