# Generated by Django 4.2.15 on 2024-10-06 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("promotion", "0001_initial"),
        ("my_admin", "0001_initial"),
        ("catalog", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="my_admin.myadmin",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="catalog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.catalog",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="promotion.promotion",
            ),
        ),
    ]
