# Generated by Django 4.2.15 on 2024-10-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("promotion", "0002_alter_promotion_table"),
        ("product", "0002_alter_product_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="promotion.promotion",
            ),
        ),
    ]
