# Generated by Django 4.2.15 on 2024-10-12 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("promotion", "0002_remove_promotion_deleted_at_promotion_delete_at"),
        ("product", "0003_remove_product_deleted_at_product_delete_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="promotion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="promotion.promotion",
            ),
        ),
    ]
