# Generated by Django 4.2.15 on 2024-10-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_promotion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="part_number",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
