# Generated by Django 4.2.15 on 2024-11-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
