# Generated by Django 4.2.15 on 2024-10-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_admin", "0002_alter_myadmin_delete_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myadmin",
            name="azure_ad",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
