# Generated by Django 4.2.15 on 2024-10-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("order_date", models.DateTimeField()),
                ("transaction_number", models.CharField(max_length=255)),
                ("amount", models.FloatField()),
                ("bank_code", models.CharField(max_length=50)),
                ("bank_status", models.CharField(max_length=50)),
                ("bank_message", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "transactions",
            },
        ),
    ]
