# Generated by Django 4.2.15 on 2024-10-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0002_alter_transaction_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="bank_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="bank_message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
