# Generated by Django 4.2.15 on 2024-10-06 06:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0002_transaction_order"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="transaction",
            table=None,
        ),
    ]
