# Generated by Django 4.2.15 on 2024-10-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0003_alter_transaction_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="created_at",
        ),
        migrations.AddField(
            model_name="transaction",
            name="delete_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
