# Generated by Django 4.2.15 on 2024-10-07 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0004_remove_transaction_created_at_transaction_delete_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="delete_at",
        ),
        migrations.AddField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
