# Generated by Django 4.2.15 on 2024-12-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_advised",
            field=models.BooleanField(default=False),
        ),
    ]
