# Generated by Django 4.2.15 on 2024-12-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="date_of_birth",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="gender",
            field=models.BooleanField(default=0),
        ),
    ]
