# Generated by Django 4.2.15 on 2024-11-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="discount_value",
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
