# Generated by Django 4.2.15 on 2024-11-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotion", "0002_alter_promotion_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
