# Generated by Django 4.2.15 on 2024-11-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotion", "0002_promotion_discount_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage Discount"),
                    ("fixed", "Fixed Discount"),
                ],
                default="percentage",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("expired", "Expired"),
                ],
                default="active",
                max_length=50,
            ),
        ),
    ]
