# Generated by Django 4.2.15 on 2024-11-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_incoming", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productincoming",
            name="cost_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productincoming",
            name="shipping_cost",
            field=models.IntegerField(default=0),
        ),
    ]
