# Generated by Django 4.2.15 on 2024-10-06 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_product_admin_product_catalog_product_promotion"),
        ("store", "0001_initial"),
        ("product_store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productstore",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="productstore",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="store.store",
            ),
        ),
    ]
