# Generated by Django 4.2.15 on 2024-10-06 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product_code", models.CharField(max_length=50)),
                ("product_name", models.CharField(max_length=255)),
                ("product_part_number", models.CharField(max_length=50)),
                ("quantity", models.IntegerField()),
                ("unit_price", models.FloatField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
