# Generated by Django 4.2.15 on 2024-12-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_detail", "0002_orderdetail_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="promotion_discount_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("percentage", "Percentage Discount"),
                    ("fixed", "Fixed Discount"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="promotion_discount_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="promotion_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
