# Generated by Django 4.2.15 on 2024-10-19 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_store_postal_code"),
        ("order_detail", "0003_remove_orderdetail_deleted_at_orderdetail_delete_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="store.store",
            ),
        ),
    ]
