# Generated by Django 4.2.15 on 2024-10-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_detail", "0004_orderdetail_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="location_pickup",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
