# Generated by Django 4.2.15 on 2024-10-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_store_postal_code"),
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="store",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="store.store"
            ),
            preserve_default=False,
        ),
    ]
