# Generated by Django 4.2.15 on 2024-11-03 04:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blog_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="status",
        ),
    ]
