# Generated by Django 4.2.15 on 2024-11-03 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_blog_slug_alter_blog_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="my_admin",
            new_name="admin",
        ),
    ]
